menoo/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', menu, name='menu'),
    path('mesa/<int:number_table>', menu, name='menu'),
    path('pedidos/', OrderList.as_view(), name="orders_menu"),
    path('pedido/<int:pk>/', OrderDetail.as_view(), name="order-detail"),
    path('deletar/', delete_food, name='delete-food')
]

''' FORMS:  '''

urlpatterns += [
    path('nova_categoria/', create_category, name='new_category'),
    path('novo_alimento/', create_food, name="new_food")
]


''' ACTIONS:  '''

urlpatterns += [
    path('visualizar_pedido/<int:pk>/', view_order, name='view-order'),
    path('deletar_pedido/<int:pk>',delete_order, name='delete-order'),
    path('deletar_todos_pedidos/',delete_all_orders,name='clean-orders')
]

'''   API - ENDPOINTS:     '''

urlpatterns += [
    path('api/order-list&status=<slug:status>/', OrdersListAPIView.as_view(), name='order-list'),
    path('api/order-retrieve/<int:id>/', OrdersRetrieveAPIView.as_view(), name='order-retrieve'),
    path('api/order-create/', OrderPostAPIView.as_view(), name='order-post'),
    ]

root/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path, include
from django.conf.urls.static import static
from django.http import HttpResponseRedirect
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-api/', include('rest_framework.urls')),
    path('menu/', include('menoo.urls')),
    path('', RedirectView.as_view(url='/menu/')),
    path('authentication/', include('django.contrib.auth.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menoo/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, RegexValidator
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(_('name'), max_length=80, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name

class Food(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(_('name'), max_length=80)
    description = models.TextField(_('Description'), max_length=250)
    price = models.FloatField(_('Price'), validators=[MinValueValidator(0.0)])
    image = models.ImageField(_('Image Food'), upload_to='foods/', default='logo.avif')

    class Meta:
        ordering = ['price']
        verbose_name = 'Alimento'
        verbose_name_plural = 'Alimentos'

    def __str__(self):
        return self.name

# Modelo intermediário para associar pedidos e comidas, permitindo duplicatas.
class OrderFood(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.food.name} (x{self.quantity})"

class Order(models.Model):
    foods = models.ManyToManyField(Food, through='OrderFood')  # Usando o modelo intermediário.
    order_date = models.DateTimeField('Data-Hora do pedido', auto_now_add=True)
    note = models.TextField(_('Observation'), blank=True, default="Nenhuma observação")
    customer_name = models.CharField(_('Customer Name'), max_length=90)
    phone_regex = RegexValidator(
        regex=r'^\d{2}\d{9}$',
        message="O número de telefone deve estar no formato: '(dd)988888888'. Até 11 dígitos são permitidos."
    )
    customer_phone_number = models.CharField(validators=[phone_regex], max_length=11)
    
    STATUS_CHOICES = [
        ('Aguardando','Aguardando'),
        ('Visto','Visto')
    ]
    
    status = models.CharField(max_length=22, default='Aguardando', choices=STATUS_CHOICES)
    table = models.IntegerField(_('Número da mesa'), default=None, blank=True, null=True)

    @property
    def preco_total(self):
        # Calcular o preço total considerando a quantidade de cada item.
        return sum(order_food.food.price * order_food.quantity for order_food in self.orderfood_set.all())


    def get_absolute_url(self):
        return reverse('order-detail', args=[str(self.id)])
    
    
    class Meta:
        ordering = ['order_date']

    def __str__(self):
        return 'Pedido: ' + str(self.id)

menoo/forms.py
from django import forms
from .models import *

class NewCategory(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')

        if name and len(name) < 5:
            raise forms.ValidationError('O nome deve ter no mínimo 5 caracteres.')

        return cleaned_data

        
class NewFood(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['category','name','description','price','image']

menoo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse    
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .models import *
from .serializers import OrderSerializer
from rest_framework.generics import ListAPIView, RetrieveAPIView, CreateAPIView
from .forms import *


def menu(request, number_table):
    
    category = Category.objects.all()
    foods = Food.objects.all().order_by('category')
    
    context = {'categories':category, 'foods':foods}

    return render(request,'menu.html',context=context)

@login_required
def create_category(request):
    
    if request.method == "POST":
        form = NewCategory(request.POST)
        if form.is_valid():
            form.save()
            return redirect('orders_menu')
    else:
        form = NewCategory()
        
    return render(request, 'form.html', context={"form":form, "title":"Categoria"})

@login_required
def create_food(request):
    
    if request.method == "POST":
        form = NewFood(request.POST, request.FILES)
        print(form)
        if form.is_valid():
            form.save()
            return redirect('orders_menu')
        
    form = NewFood()
    return render(request, 'form.html', context={"form":form, "title":"Alimento"})
        

def delete_food(request):
    
    
    categories = Category.objects.all()
    foods = Food.objects.all()
    
    context = {"categories":categories, "foods":foods}
    
    if request.method == "POST":
        categorie = request.POST.get('select-categories')
        
        if not categorie == "None" and categorie:
            categorie_obj = Category.objects.get(pk=categorie)
            categorie_obj.delete()  
                    
         
        ########################
        
        food = request.POST.get('select-foods') 
        if not food == "None" and food:
            food_obj = Food.objects.get(pk=food)
            food_obj.delete()
        

    
    return render(request,'delete-form.html',context=context)


class OrderList(LoginRequiredMixin, ListView):
    
    queryset = Order.objects.all().order_by('-order_date')
    template_name = 'menu_orders.html'
    context_object_name = 'orders'
    paginate_by = 21
    
class OrderDetail(LoginRequiredMixin, DetailView):
    
    model = Order
    template_name = 'order-detail.html'
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["foods"] = OrderFood.objects.filter(order_id=self.object.id)
        return context
    
    
    
@require_POST   
def view_order(request,pk):
    
    obj = Order.objects.get(pk=pk)
    obj.status = "Visto"
    obj.save()
    
    return redirect(request.POST.get('current'))

@require_POST
def delete_order(request,pk):
    
    obj = Order.objects.get(pk=pk)
    obj.delete()
    return redirect('orders_menu')

@require_POST
def delete_all_orders(request):
    
    obj = Order.objects.all()
    obj.delete()
    return redirect('orders_menu')
    


'''   API    '''
class OrdersListAPIView(ListAPIView):
    
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    
    def get_queryset(self):
        status = self.kwargs.get('status', None)
        if status is not None:
            match status:
                case 'ag':
                    return self.queryset.filter(status='Aguardando Atendimento')
    
                case 'pg':
                    return self.queryset.filter(status='Pago')
    
                case 'et':
                    return self.queryset.filter(status='Entregue')
    
                case 'ep':
                    return self.queryset.filter(status='Em Preparo')
                
                case _:
                    return self.queryset.all()
                
                    
class OrdersRetrieveAPIView(RetrieveAPIView):
    
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    
    def get_object(self):
        return self.queryset.get(id=self.kwargs.get('id'))
    
    
class OrderPostAPIView(CreateAPIView):
    
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

menoo/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{%endblock%}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {%block extra_styles %} {%endblock%}
</head>

<body>
    
    <header>
        <button class="side-button"><i class="bi bi-water"></i></button>
        <p class="title">Restaurant</p>
    </header>


    <div class="side-menu">
        <img id="logo" src="/static/logo.avif">
        <h2 class="name"><i class="fa-solid fa-plate-utensils"></i>Restaurant</h2>
        <p class="social"><i class="bi bi-instagram"></i> @Restaurant</p>
        <p class="social"><i class="bi bi-facebook"></i> Restaurant97</p>
        <br>
        <p class="social" style="font-size:1.5rem;"><i class="bi bi-clock-history"></i> 19:30 - 23:30</p>
    </div>

    <div class="slide-categories">
        <div class="categories-wrapper">
            <a href="#Bebidas">Bebidas</a>
            <a href="#Entradas">Entradas</a>
            <a href="#Petiscos">Petiscos</a>
            <a href="#Pratos Principais">Pratos Principais</a>
            <a href="#Sobremesas">Sobremesas</a>
        </div>
    </div>

    {% block content %}
    
    {% endblock %}

    <script src="{% static "js/base.js" %}"></script>
    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>

</html>

menoo/templates/delete-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static "css/form.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&display=swap" rel="stylesheet">
</head>
<body>
    <a class="back" href="{% url "orders_menu" %}"><i class="bi bi-arrow-left-circle-fill"></i></a>
    <div class="container">
        {% if form.non_field_errors %}
        <div class="non-field-errors">
            {% for err in form.non_field_errors %}
            <p class="form-error">{{ err }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <h1>Deletar Categoria</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <select name="select-categories">
                <option selected value="None">Nenhum valor selecionado</option>
                {% for categorie in categories %}
                <option value="{{categorie.pk}}">{{categorie.name}}</option>
                {% endfor %}
              </select>

            <button type="submit">Deletar</button>

            

        </form>

        <br>
        <br>

        <h1>Deletar Alimento</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <select name="select-foods">
                <option selected value="None">Nenhum valor selecionado</option>
                {% for food in foods %}
                <option value="{{food.pk}}">{{food.name}}</option>
                {% endfor %}
              </select>

              <button type="submit">Deletar</button>

        </form>


    </div>
</body>
</html>

menoo/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static "css/form.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&display=swap" rel="stylesheet">
</head>
<body>
    <a class="back" href="{% url "orders_menu" %}"><i class="bi bi-arrow-left-circle-fill"></i></a>
    <div class="container">
        {% if form.non_field_errors %}
        <div class="non-field-errors">
            {% for err in form.non_field_errors %}
            <p class="form-error">{{ err }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <h1>Criar {{title}}</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Criar</button>
        </form>
    </div>
</body>
</html>

menoo/templates/menu.html
{% extends "base.html" %}
{% load static %}

{%block extra_styles%}
<link rel="stylesheet" href="{% static "css/menu.css" %}">
<link rel="stylesheet" href="{% static "css/modal.css" %}">{%endblock%}

{%block title%}Menu{%endblock%}

{% block extra_scripts %}
<script src="{% static "js/script.js" %}"></script>
{% endblock %}

{% block content %}
<br>
<div class="main-container">
    <div class="start">
        <img src="/static/logo.avif">
        <h1>Restaurant</h1>
    </div>
    <section class="info-box">
        <p><i class="bi bi-geo-fill"></i>&nbspCentro, Rua Bonitinha, 150</p>
        <p><i class="bi bi-clock-fill"></i></i>&nbspEntrega: 20-30 minutos</p>
        <p id="time" class="open">Aberto</p>
    </section>
    <br>
    {% regroup foods by category as food_list %}

    {% for food in food_list%}
    <h2 class="category" id="{{food.grouper}}">{{food.grouper}}</h2>
    <div class="food-list">
        {% for food in food.list %}
        <div class="food-item">
            <img class="food-image" src="{{food.image.url}}">
            <div class="food-details">
                <p class="price" id="{{food.price}}" style="font-size:1.5rem;"><span>R$&nbsp</span>{{food.price}}</p>
                <h3 class="food-name" id="{{food.id}}">{{food.name}}</h3>
                <p class="food-description">{{food.description}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
<br>

<div class="modal-container">
    <div class="modal-content">
        <i class="bi bi-x-lg close-modal"></i>
        <img class="logo-modal" src="">
        <h2 class="modal-title">Caipirinha</h2>
        <p class="modal-price" style="font-size:2rem;">R$ 90</p>
        <p class="modal-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
            been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book. It has survived not only five centuries,</p>
        <button class="btn_add" name="empty">Adicionar ao Carrinho</button>
        <p>No carrinho:&nbsp<span class="count"></span></p>
    </div>
</div>

<div class="cart">
    <i class="bi bi-basket2"></i>
</div>

<div class="cart-modal">
    <div class="cart-content">
        <i class="bi bi-x close-cart"></i>

        <div class="start-cart">
            <div style="text-align:center">
                <i class="bi bi-basket2-fill"></i>
            </div>
            <div style="text-align:center">
                <h1>Sua cestinha</h1>
            </div>
            <ul class="products-list">
            </ul>
            <div class="divBtn">
                <button class="next"><i class="bi bi-chevron-double-right"></i></button>
            </div>
        </div>

        <div class="mid-cart">
            <div>
                <div class="form">
                    <div class="errors">
                        <ul id="errors-list">
                        </ul>
                    </div>
                    <label>Seu Nome&nbsp<i class="bi bi-person-walking"></i></label>
                    <br>
                    <input id="name" required type="text" placeholder="João Fulano">
                </div>

                <div class="form">
                    <label>Seu Número&nbsp<i class="bi bi-telephone-fill"></i></label>
                    <br>
                    <input id="number" required type="text" placeholder="46999999999">
                </div>

                <div class="form">
                <label>Observação &nbsp<i class="bi bi-clipboard2-minus-fill"></i></label>
                <br>
                <textarea rows="4" cols="50" placeholder="(opcional) Não quero cebola xD" id="note"></textarea>
                </div>
                <button id="finish"><i class="bi bi-check-circle-fill"></i></button>
            </div>
        </div>

        <div class="end-cart" style="display:none;">
            <i class="bi bi-hypnotize loading" id="finish-icon"></i>
            <br>
            <p class="end-text" id="finish-order"></p>
        </div>
    </div>
</div>

{% endblock %}

menoo/templates/menu_orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pedidos</title>
    <link rel="stylesheet" href="{% static "css/menu-orders.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar">
        <a href="{% url "new_category" %}" class="add"><p>Nova Categoria</p><i class="bi bi-plus-circle"></i></a>
        <a href="{% url "new_food" %}" class="add"><p>Novo Alimento</p><i class="bi bi-plus-circle"></i></a>
        <a href="{% url "delete-food" %}" class="add"><p>Deletar</p><i style="padding:17px;" class="bi bi-trash3-fill"></i></a>
    </nav>
    <br>
    <h1 class="orders-title">PEDIDOS</h1>

    <section class="orders">
    {% for order in orders %}
        <a href="{{order.get_absolute_url}}" style="text-decoration:none;color:black;">
            <div class="order-card {% if order.status == "Visto" %}visto{% endif %}">
                <p class="order-id">#{{order.id}}</p>
                <p class="order-customer"><i class="bi bi-person-fill"></i>&nbsp{{order.customer_name|truncatechars:20}}</p>
                <p class="order-price">R$ {{order.preco_total}}</p>
                <p class="order-table"><?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
                    <svg fill="#000000" width="27px" height="27px" viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M10.585938 11L0.38085938 21.205078 A 1.0001 1.0001 0 0 0 0.18945312 21.396484L0 21.585938L0 21.832031 A 1.0001 1.0001 0 0 0 0 22.158203L0 28L3 28L3 50L9 50L9 28L11 28L11 43L17 43L17 28L33 28L33 43L39 43L39 28L41 28L41 50L47 50L47 28L50 28L50 22.167969 A 1.0001 1.0001 0 0 0 50 21.841797L50 21.585938L49.806641 21.392578 A 1.0001 1.0001 0 0 0 49.623047 21.207031 A 1.0001 1.0001 0 0 0 49.617188 21.203125L39.414062 11L39 11L10.585938 11 z M 11.414062 13L38.585938 13L46.585938 21L3.4140625 21L11.414062 13 z M 2 23L48 23L48 26L46.167969 26 A 1.0001 1.0001 0 0 0 45.841797 26L42.154297 26 A 1.0001 1.0001 0 0 0 41.984375 25.986328 A 1.0001 1.0001 0 0 0 41.839844 26L38.167969 26 A 1.0001 1.0001 0 0 0 37.841797 26L34.154297 26 A 1.0001 1.0001 0 0 0 33.984375 25.986328 A 1.0001 1.0001 0 0 0 33.839844 26L16.167969 26 A 1.0001 1.0001 0 0 0 15.841797 26L12.154297 26 A 1.0001 1.0001 0 0 0 11.984375 25.986328 A 1.0001 1.0001 0 0 0 11.839844 26L8.1679688 26 A 1.0001 1.0001 0 0 0 7.8417969 26L4.1542969 26 A 1.0001 1.0001 0 0 0 3.984375 25.986328 A 1.0001 1.0001 0 0 0 3.8398438 26L2 26L2 23 z M 5 28L7 28L7 48L5 48L5 28 z M 13 28L15 28L15 41L13 41L13 28 z M 35 28L37 28L37 41L35 41L35 28 z M 43 28L45 28L45 48L43 48L43 28 z"/></svg>&nbsp{{order.table}}</p>
            </div>
        </a>
    {% endfor %}
    </section>

    <div class="div-pagination">
        <div class="pagination" style="display:flex; justify-content:center;">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                        <button class="btn_page">Anterior</button>
                    </a>
                {% endif %}
                <span class="page-current" style="color:white;">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">
                        <button class="btn_page">Próximo</button>
                    </a>
                {% endif %}
            </span>
        </div>
    </div>

    {% if orders.count > 0%}
    <button style="margin-left:2rem" class="finish-order btn"><i class="bi bi-trash"></i> Limpar Pedidos</button>
    {% endif %}

    <div class="modal-menu">
        <i class="bi bi-exclamation-diamond-fill"></i>
        <h3>Tem certeza que deseja <strong style="color:#a70202">excluir todos</strong> os pedidos?</h3>
        <br>
        <div>
            <button style="margin-top:0rem;"class="not-finish btn">Não</button>
            <form method="post" action="{% url "clean-orders" %}">
                {% csrf_token %}
                <button style="margin-top:0rem;display:inline-block;" class="finish-order btn">Sim</button>
            </form>
    </div>
    </div>

    <script src="{% static "js/menu-order.js" %}"></script>
</body>
</html>